### PR TITLE
updates detail page to support 3 years of data

### LINKED ISSUE #218: Style to fit data for three years
Allow for three years to display side-by-side on detail page (navigated to from 'full report' map popup) and in map popup.

### PR DESCRIPTION
**Pull request by designmatty**
fixes #218

2017-08-09-12-49-localhost-9000

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Neat! Any changes for the map popup? I was a bit concerned that it wouldn't look right on mobile displays if simply made wider.

**Comment by designmatty** [comment]
No changes for the popup. I talked with Jessica right before pushing this up and she had this to say:

> we're going to stick with two years on the pop-up (we just haven't gone back to that since we've been waiting for the contract)

**Comment by flibbertigibbet** [comment]
Ah okay, that makes sense.

**Comment by designmatty** [comment]
oh sorry. saw thumbs up on the previous comment and wrongly assumed that meant 👍

**Pull request merged**
