### PR TITLE
Feature/kak/remote configuration#213

### LINKED ISSUE #213: Move hard-coded year references
In the files:
```
app/scripts/cartodb/cartodb-api-config.js
app/scripts/years/year_service.js
```

there are hard-coded references to the available years and summary statistics for each year.

Make configurable by moving those values possibly to a new CartoDB summary table, or to a configuration file on S3.

### LINKED ISSUE #217: Parameterize years in description
Modify `app/scripts/views/info/info-partial.html` to parameterize the years in the app.

Could modify to read "for the {start} to {end} calendar years" instead of listing them individually.

### LINKED ISSUE #234: Parmeterize static statistics strings
In the same manner as #217, move the summary statistic text to a place where it may be externally edited.

This text was modified in code in #225 .

### PR DESCRIPTION
**Pull request by flibbertigibbet**
Get the years and associated yearly summary statistics and data download URLs from a new Carto table, so they may be externally configured independent of the application code.

What the new table looks like:
mos_years_carto_table

Closes #213 
Closes #217 
Closes #234

### CODE REVIEW

**Comment by CloudNiner** [comment]
I think I found a bug:

1. Switch to "map" view
2. Change the year being viewed
3. Return to "charts" view by clicking link in navbar

You get:
screen shot 2017-10-03 at 09 43 45

If you change the year selector while on the charts page, it seems to update the chart data appropriately. Other views seem to work fine as well.

**Comment by CloudNiner** [comment]
Is there no 2015 data available for download?

screen shot 2017-10-03 at 09 43 58

**Comment by flibbertigibbet** [comment]
Right, there is no 2015 data download available, as it hasn't been uploaded for public consumption yet by the city. The URL is null in the Carto table. Also it looks like the download link for 2013 is broken now (it is still set).

Good find on the charts navigation.

**Comment by flibbertigibbet** [comment]
Not sure how we missed that before, but the charts navigation issue is also present on both staging and the [production site](http://visualization.phillybuildingbenchmarking.com/#/), which we haven't updated since the original release.

image

**Pull request merged**
